name: Manual - Semantic Release

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Branch Reference
        default: main
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
        if: github.event.inputs.git-ref == 'main'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
        if: github.event.inputs.git-ref == 'main'

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
        if: github.event.inputs.git-ref == 'main'

      - name: Release
        run: |
          cp ${{ github.workspace }}/.github/config/.releaserc.json .
          npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.inputs.git-ref == 'main'
